---
apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-configuration
  labels:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/part-of: factorio
data:
  server-settings.json: |
    {
      "name": "WFH COVID-19",

      "_comment_autosave_interval": "Autosave interval in minutes",
      "autosave_interval": 15,

      "_comment_autosave_slots": "server autosave slots, it is cycled through when the server autosaves.",
      "autosave_slots": 4
    }
  map-settings.json: |
    {
      "difficulty_settings":
      {
        "recipe_difficulty": 0,
        "technology_difficulty": 0,
        "technology_price_multiplier": 1,
        "research_queue_setting": "after-victory"
      },
      "pollution":
      {
        "enabled": true,
        "_comment_min_to_diffuse_1": "these are values for 60 ticks (1 simulated second)",
        "_comment_min_to_diffuse_2": "amount that is diffused to neighboring chunk",
        "diffusion_ratio": 0.02,
        "min_to_diffuse": 15,
        "ageing": 1,
        "expected_max_per_chunk": 150,
        "min_to_show_per_chunk": 50,
        "min_pollution_to_damage_trees": 60,
        "pollution_with_max_forest_damage": 150,
        "pollution_per_tree_damage": 50,
        "pollution_restored_per_tree_damage": 10,
        "max_pollution_to_restore_trees": 20,
        "enemy_attack_pollution_consumption_modifier": 1
      },
      "enemy_evolution":
      {
        "enabled": true,
        "time_factor": 0.000004,
        "destroy_factor": 0.002,
        "pollution_factor": 0.0000009
      },
      "enemy_expansion":
      {
        "enabled": true,
        "min_base_spacing": 3,
        "max_expansion_distance": 7,
        "friendly_base_influence_radius": 2,
        "enemy_building_influence_radius": 2,
        "building_coefficient": 0.1,
        "other_base_coefficient": 2.0,
        "neighbouring_chunk_coefficient": 0.5,
        "neighbouring_base_chunk_coefficient": 0.4,
        "max_colliding_tiles_coefficient": 0.9,
        "settler_group_min_size": 5,
        "settler_group_max_size": 20,
        "min_expansion_cooldown": 14400,
        "max_expansion_cooldown": 216000
      },
      "unit_group":
      {
        "min_group_gathering_time": 3600,
        "max_group_gathering_time": 36000,
        "max_wait_time_for_late_members": 7200,
        "max_group_radius": 30.0,
        "min_group_radius": 5.0,
        "max_member_speedup_when_behind": 1.4,
        "max_member_slowdown_when_ahead": 0.6,
        "max_group_slowdown_factor": 0.3,
        "max_group_member_fallback_factor": 3,
        "member_disown_distance": 10,
        "tick_tolerance_when_member_arrives": 60,
        "max_gathering_unit_groups": 30,
        "max_unit_group_size": 200
      },
      "steering":
      {
        "default":
        {
          "radius": 1.2,
          "separation_force": 0.005,
          "separation_factor": 1.2,
          "force_unit_fuzzy_goto_behavior": false
        },
        "moving":
        {
          "radius": 3,
          "separation_force": 0.01,
          "separation_factor": 3,
          "force_unit_fuzzy_goto_behavior": false
        }
      },
      "path_finder":
      {
        "fwd2bwd_ratio": 5,
        "goal_pressure_ratio": 2,
        "max_steps_worked_per_tick": 100,
        "max_work_done_per_tick": 8000,
        "use_path_cache": true,
        "short_cache_size": 5,
        "long_cache_size": 25,
        "short_cache_min_cacheable_distance": 10,
        "short_cache_min_algo_steps_to_cache": 50,
        "long_cache_min_cacheable_distance": 30,
        "cache_max_connect_to_cache_steps_multiplier": 100,
        "cache_accept_path_start_distance_ratio": 0.2,
        "cache_accept_path_end_distance_ratio": 0.15,
        "negative_cache_accept_path_start_distance_ratio": 0.3,
        "negative_cache_accept_path_end_distance_ratio": 0.3,
        "cache_path_start_distance_rating_multiplier": 10,
        "cache_path_end_distance_rating_multiplier": 20,
        "stale_enemy_with_same_destination_collision_penalty": 30,
        "ignore_moving_enemy_collision_distance": 5,
        "enemy_with_different_destination_collision_penalty": 30,
        "general_entity_collision_penalty": 10,
        "general_entity_subsequent_collision_penalty": 3,
        "extended_collision_penalty": 3,
        "max_clients_to_accept_any_new_request": 10,
        "max_clients_to_accept_short_new_request": 100,
        "direct_distance_to_consider_short_request": 100,
        "short_request_max_steps": 1000,
        "short_request_ratio": 0.5,
        "min_steps_to_check_path_find_termination": 2000,
        "start_to_goal_cost_multiplier_to_terminate_path_find": 500.0
      },
      "max_failed_behavior_count": 3
    }
  map-gen-settings.json: |
    {
      "_terrain_segmentation_comment": "Inverse of map scale",
      "terrain_segmentation": 1,
      
      "_water_comment":
      [
        "Multiplier for water 'coverage' - higher increases the water level.",
        "Water level = 10 * log2(this value)"
      ],
      "water": 1,
      
      "_comment_width+height": "Width and height of map, in tiles; 0 means infinite",
      "width": 0,
      "height": 0,
      
      "_starting_area_comment": "Multiplier for 'biter free zone radius'",
      "starting_area": 1,
      
      "peaceful_mode": false,
      
      "autoplace_controls":
      {
        "coal": {"frequency": 1, "size": 1, "richness": 1},
        "stone": {"frequency": 1, "size": 1, "richness": 1},
        "copper-ore": {"frequency": 1, "size": 1,"richness": 1},
        "iron-ore": {"frequency": 1, "size": 1, "richness": 1},
        "uranium-ore": {"frequency": 1, "size": 1, "richness": 1},
        "crude-oil": {"frequency": 1, "size": 1, "richness": 1},
        "trees": {"frequency": 1, "size": 1, "richness": 1},
        "enemy-base": {"frequency": 1, "size": 1, "richness": 1}
      },
      
      "cliff_settings":
      {
        "_name_comment": "Name of the cliff prototype",
        "name": "cliff",
        
        "_cliff_elevation_0_comment": "Elevation of first row of cliffs",
        "cliff_elevation_0": 10,
        
        "_cliff_elevation_interval_comment": "Elevation difference between successive rows of cliffs",
        "cliff_elevation_interval": 10,
        
        "_richness_comment": "Multiplier for cliff continuity; 0 will result in no cliffs, 10 will make all cliff rows completely solid",
        "richness": 1
      },
      
      "_property_expression_names_comment":
      [
        "Overrides for property value generators",
        "Elevation influences water and cliff placement.",
        "Leave it blank to get 'normal' terrain.",
        "Use '0_16-elevation' to reproduce terrain from 0.16.",
        "Use '0_17-island' to get an island."
      ],
      "property_expression_names":
      {
        "elevation": "0_17-island",
        
        "control-setting:aux:bias": "0.300000",
        "control-setting:aux:frequency:multiplier": "1.333333",
        "control-setting:moisture:bias": "0.100000",
        "control-setting:moisture:frequency:multiplier": "0.500000"
      },
      
      "starting_points":
      [
        {"x": 1000, "y": 2000}
      ],
      
      "_seed_comment": "Use null for a random seed, number for a specific seed.",
      "seed": null
    }
  server-whitelist.json: |
    [
      "bhx8e2n0dha1"
    ]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio
  labels:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/part-of: factorio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: factorio
      app.kubernetes.io/part-of: factorio
  serviceName: factorio
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: factorio
        app.kubernetes.io/part-of: factorio
    spec:
      initContainers:
        - name: create-default-save
          image: docker.pkg.github.com/sjparkinson/factorio/factorio:latest
          command:
            - /opt/factorio/bin/x64/factorio
            - --create
            - saves/default.zip
          volumeMounts:
            - name: saves
              mountPath: /opt/factorio/saves
      containers:
        - name: factorio
          image: docker.pkg.github.com/sjparkinson/factorio/factorio:latest
          command:
            - /opt/factorio/bin/x64/factorio
            - --start-server
            - saves/default.zip
            - --use-server-whitelist
            - --server-whitelist
            - /etc/factorio/server-whitelist.json
            - --server-adminlist
            - /etc/factorio/server-whitelist.json
            - --server-settings
            - /etc/factorio/server-settings.json
            - --map-settings
            - /etc/factorio/map-settings.json
            - --map-gen-settings
            - /etc/factorio/map-gen-settings.json
          stdin: true
          tty: true
          securityContext:
            capabilities:
              drop:
                - ALL
          ports:
            - name: factorio
              containerPort: 34197
              protocol: UDP
          volumeMounts:
            - name: saves
              mountPath: /opt/factorio/saves
            - name: config
              mountPath: /etc/factorio
          resources:
            requests:
              cpu: 30m
              memory: 128Mi
      imagePullSecrets:
        - name: github
      volumes:
        - name: config
          configMap:
            name: factorio-configuration
  volumeClaimTemplates:
    - metadata:
        name: saves
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  labels:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/part-of: factorio
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/part-of: factorio
  ports:
    - name: factorio
      protocol: UDP
      port: 34197
      targetPort: 34197
      nodePort: 31197
  externalIPs:
    - 159.65.212.70